name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Setup DotNet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x

    - name: Restore Tools
      run: dotnet tool restore

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build Project
      run: dotnet build --no-restore

    - name: Run Tests
      run: dotnet test --no-build --verbosity normal

    - name: Run InspectCode
      run: dotnet jb inspectcode --no-build --swea --severity=SUGGESTION --format="xml" --output="inspectcode.xml" *.sln

    - name: Run NVika
      run: dotnet nvika parsereport "inspectcode.xml"
